/**
 * Base de datos de productos de Distribuciones La Montaña SAS (La Montaña Aaron)
 * Extraída íntegramente del inventario oficial de la empresa (NIT: 901712016)
 * Incluye las 53 referencias reales con sus 4 escalas de precio por volumen.
 */

const PRODUCTS_DATA = [
  // --- LÁCTEOS Y DERIVADOS ---
  {
    id: "prod-1578",
    code: "1578",
    name: "Queso Mozzarella Tajado La Montaña Aaron",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Top Ventas",
    badgeColor: "#C1121F",
    ribbonColor: "#F59E0B",
    presentation: "1.250 gr (140 lonchas)",
    weightGrams: 1250,
    priceUnit: 28000,
    price6: 27000,
    price12: 26800,
    priceWholesale: 26500,
    inStock: true,
    description: "Queso mozzarella hilado tradicional con excelente fundido y sabor lácteo natural. Ideal para pizzerías, sándwiches y lasañas.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: true
  },
  {
    id: "prod-1036",
    code: "1036",
    name: "Queso Mozzarella Tajado La Montaña Aaron 2.5 Kg",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Formato HORECA",
    badgeColor: "#0284C7",
    ribbonColor: "#F59E0B",
    presentation: "2.5 Kg en láminas",
    weightGrams: 2500,
    priceUnit: 54000,
    price6: 53000,
    price12: 52000,
    priceWholesale: 51000,
    inStock: true,
    description: "Presentación institucional de alto rendimiento para cadenas de restaurantes, hoteles y casinos.",
    image: "assets/images/products/mozzarella_barra.svg",
    popular: true
  },
  {
    id: "prod-1039",
    code: "1039",
    name: "Queso en Barra La Montaña Aaron",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Rendimiento Extra",
    badgeColor: "#059669",
    ribbonColor: "#F59E0B",
    presentation: "Barra 2.500 gr",
    weightGrams: 2500,
    priceUnit: 51000,
    price6: 50000,
    price12: 49500,
    priceWholesale: 49000,
    inStock: true,
    description: "Barra compacta uniforme de queso semigraso para tajado industrial o rallado fino.",
    image: "assets/images/products/mozzarella_barra.svg",
    popular: true
  },
  {
    id: "prod-100002",
    code: "100002",
    name: "Queso Tajado Mozzarella Bosconia",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Recomendado",
    badgeColor: "#D97706",
    ribbonColor: "#F59E0B",
    presentation: "2.5 Kg (120 lonchas)",
    weightGrams: 2500,
    priceUnit: 59000,
    price6: 58500,
    price12: 58500,
    priceWholesale: 57800,
    inStock: true,
    description: "Marca aliada Bosconia, lonchas consistentes que no se pegan y gratina con dorado dorado uniforme.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },
  {
    id: "prod-100001",
    code: "100001",
    name: "Queso Tajado Mozzarella Medio Bosconia",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Económico",
    badgeColor: "#4B5563",
    ribbonColor: "#F59E0B",
    presentation: "1.250 gr",
    weightGrams: 1250,
    priceUnit: 30000,
    price6: 29500,
    price12: 29000,
    priceWholesale: 28000,
    inStock: true,
    description: "Lonchas intermedias de alta resistencia al calor y fundición cremosa.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },
  {
    id: "prod-1025",
    code: "1025",
    name: "Queso Bosconia en Barra",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Panaderías",
    badgeColor: "#059669",
    ribbonColor: "#F59E0B",
    presentation: "Barra 2.500 gr",
    weightGrams: 2500,
    priceUnit: 56000,
    price6: 55500,
    price12: 55300,
    priceWholesale: 55000,
    inStock: true,
    description: "Barra entera ideal para procesadores de alimentos, panaderías y pizzerías artesanales.",
    image: "assets/images/products/mozzarella_barra.svg",
    popular: false
  },
  {
    id: "prod-445050",
    code: "445050",
    name: "Queso en Bloque El Corral",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Línea Premium",
    badgeColor: "#7C3AED",
    ribbonColor: "#F59E0B",
    presentation: "Bloque 2.500 gr",
    weightGrams: 2500,
    priceUnit: 51000,
    price6: 50000,
    price12: 49500,
    priceWholesale: 49000,
    inStock: true,
    description: "Bloque de queso fresco semi-curado de consistencia firme, sabor pronunciado y agradable paladar.",
    image: "assets/images/products/mozzarella_barra.svg",
    popular: true
  },
  {
    id: "prod-1040",
    code: "1040",
    name: "Queso Tajado Mozzarella",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Hogar",
    badgeColor: "#2563EB",
    ribbonColor: "#F59E0B",
    presentation: "490 gr (20 lonchas)",
    weightGrams: 490,
    priceUnit: 14000,
    price6: 13500,
    price12: 13000,
    priceWholesale: 12500,
    inStock: true,
    description: "Formato familiar para desayunos y meriendas, empacado al vacío para máxima frescura.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },
  {
    id: "prod-1041",
    code: "1041",
    name: "Queso Tajado Mozzarella",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Práctico",
    badgeColor: "#6B7280",
    ribbonColor: "#F59E0B",
    presentation: "250 gr (10 lonchas)",
    weightGrams: 250,
    priceUnit: 7000,
    price6: 6800,
    price12: 6700,
    priceWholesale: 6500,
    inStock: true,
    description: "Presentación individual ideal para tiendas de barrio y consumo diario.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },
  {
    id: "prod-10001",
    code: "10001",
    name: "Queso Tajado Mozzarella Mini",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Minimercados",
    badgeColor: "#6B7280",
    ribbonColor: "#F59E0B",
    presentation: "125 gr (5 lonchas)",
    weightGrams: 125,
    priceUnit: 4500,
    price6: 4400,
    price12: 4300,
    priceWholesale: 4200,
    inStock: true,
    description: "Porción pequeña y accesible, ideal para loncheras y sándwiches express.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },
  {
    id: "prod-253645",
    code: "253645",
    name: "Suero Costeño La Montaña Tradicional",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Receta Artesanal",
    badgeColor: "#059669",
    ribbonColor: "#10B981",
    presentation: "Vaso 500 gr",
    weightGrams: 500,
    priceUnit: 4500,
    price6: 4300,
    price12: 4200,
    priceWholesale: 4000,
    inStock: true,
    description: "Auténtico suero costeño elaborado con leche fresca pasteurizada, textura espesa y la acidez perfecta para acompañar arepas, yuca y patacones.",
    image: "assets/images/products/suero_costeno.svg",
    popular: true
  },
  {
    id: "prod-1024",
    code: "1024",
    name: "Suero Costeño La Montaña Formato Litro",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Ahorro Familiar",
    badgeColor: "#059669",
    ribbonColor: "#10B981",
    presentation: "Envase 1.000 gr",
    weightGrams: 1000,
    priceUnit: 6500,
    price6: 6300,
    price12: 6000,
    priceWholesale: 5500,
    inStock: true,
    description: "Mayor cantidad al mejor precio. Muy solicitado por asaderos, piqueteaderos y amantes de la buena comida costeña.",
    image: "assets/images/products/suero_costeno.svg",
    popular: true
  },
  {
    id: "prod-32538",
    code: "32538",
    name: "Yogurt Sixpack Surtido",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Lonchera",
    badgeColor: "#DB2777",
    ribbonColor: "#EC4899",
    presentation: "Sixpack x 6 unidades",
    weightGrams: 900,
    priceUnit: 6500,
    price6: 6200,
    price12: 6000,
    priceWholesale: 5800,
    inStock: true,
    description: "Yogurt cremoso con pulpa de fruta natural en prácticos vasitos para la familia.",
    image: "assets/images/products/yogurt.svg",
    popular: false
  },
  {
    id: "prod-2050",
    code: "2050",
    name: "Yogur Galón Familiar",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Gran Formato",
    badgeColor: "#DB2777",
    ribbonColor: "#EC4899",
    presentation: "Garrafa 1.750 gr",
    weightGrams: 1750,
    priceUnit: 13000,
    price6: 12000,
    price12: 11500,
    priceWholesale: 11000,
    inStock: true,
    description: "Bebida láctea con fermentos vivos y sabor frutal refrescante para toda la semana.",
    image: "assets/images/products/yogurt.svg",
    popular: false
  },
  {
    id: "prod-25420",
    code: "25420",
    name: "Recorte de Queso Mozzarella",
    category: "lacteos",
    categoryName: "Quesos y Lácteos",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "Bolsa x Kilo",
    weightGrams: 1000,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Recorte limpio de mozzarella para fundir en arepas o rellenos de empanadas. Temporalmente fuera de stock.",
    image: "assets/images/products/mozzarella_tajado.svg",
    popular: false
  },

  // --- CÁRNICOS, CHORIZOS Y EMBUTIDOS ---
  {
    id: "prod-1095",
    code: "1095",
    name: "Chorizo Santarrosano Tradicional (5 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Top Ventas",
    badgeColor: "#C1121F",
    ribbonColor: "#DC2626",
    presentation: "500 gr (5 unidades)",
    weightGrams: 500,
    priceUnit: 10000,
    price6: 9800,
    price12: 9500,
    priceWholesale: 9000,
    inStock: true,
    description: "100% carne de cerdo seleccionada picada en trozo tradicional, sazón típica de Santa Rosa de Cabal. Ahumado sutil y jugoso.",
    image: "assets/images/products/chorizo_santarrosano.svg",
    popular: true
  },
  {
    id: "prod-1038",
    code: "1038",
    name: "Chorizo Santarrosano Coctel / Porción (10 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Para Picar",
    badgeColor: "#C1121F",
    ribbonColor: "#DC2626",
    presentation: "500 gr (10 unidades)",
    weightGrams: 500,
    priceUnit: 10000,
    price6: 9800,
    price12: 9500,
    priceWholesale: 9000,
    inStock: true,
    description: "Misma receta auténtica santarrosana en tamaño cóctel, ideal para picadas criollas y asados.",
    image: "assets/images/products/chorizo_santarrosano.svg",
    popular: true
  },
  {
    id: "prod-1110",
    code: "1110",
    name: "Chorizo Mexicano Especiado (5 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Sabor Intenso",
    badgeColor: "#B91C1C",
    ribbonColor: "#EF4444",
    presentation: "500 gr (5 unidades)",
    weightGrams: 500,
    priceUnit: 10000,
    price6: 9800,
    price12: 9500,
    priceWholesale: 9000,
    inStock: true,
    description: "Chorizo artesanal con toque de pimentón paprika y especias mexicanas para un sabor vibrante al asador.",
    image: "assets/images/products/chorizo_mexicano.svg",
    popular: true
  },
  {
    id: "prod-1201",
    code: "1201",
    name: "Chorizo Mexicano Porción (10 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Restaurantes",
    badgeColor: "#B91C1C",
    ribbonColor: "#EF4444",
    presentation: "500 gr (10 unidades)",
    weightGrams: 500,
    priceUnit: 10000,
    price6: 9800,
    price12: 9500,
    priceWholesale: 9000,
    inStock: true,
    description: "Formato de 10 unidades para taquerías, picadas y entradas de restaurantes campestres.",
    image: "assets/images/products/chorizo_mexicano.svg",
    popular: false
  },
  {
    id: "prod-1044",
    code: "1044",
    name: "Chorizo Casero Campesino (3 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Casero",
    badgeColor: "#D97706",
    ribbonColor: "#DC2626",
    presentation: "325 gr (3 unidades)",
    weightGrams: 325,
    priceUnit: 6500,
    price6: 6300,
    price12: 6100,
    priceWholesale: 5800,
    inStock: true,
    description: "Embutido con sabor a leña y hierbas campesinas de la cordillera.",
    image: "assets/images/products/chorizo_santarrosano.svg",
    popular: false
  },
  {
    id: "prod-1011",
    code: "1011",
    name: "Chorizo Parrillero de Cerdo (12 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Parrillada",
    badgeColor: "#EA580C",
    ribbonColor: "#DC2626",
    presentation: "1.300 gr (12 unidades)",
    weightGrams: 1300,
    priceUnit: 21000,
    price6: 20500,
    price12: 20000,
    priceWholesale: 19000,
    inStock: true,
    description: "Chorizos de gran calibre elaborados exclusivamente con carne magra de cerdo y grasa dorsal fresca.",
    image: "assets/images/products/chorizo_santarrosano.svg",
    popular: true
  },
  {
    id: "prod-1014",
    code: "1014",
    name: "Chorizo en Colágeno Mayorista (125 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Super Mayorista",
    badgeColor: "#7C3AED",
    ribbonColor: "#DC2626",
    presentation: "Bolsón 5 Kg / 10 Lb (125 Un)",
    weightGrams: 5000,
    priceUnit: 38000,
    price6: 37000,
    price12: 35000,
    priceWholesale: 34000,
    inStock: true,
    description: "Envoltura en colágeno comestible de cocción pareja. Ideal para asaderos y eventos masivos.",
    image: "assets/images/products/bolson_embutidos.svg",
    popular: false
  },
  {
    id: "prod-1016",
    code: "1016",
    name: "Bolsón Chorizo Plástica Mayorista (120 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Mayorista HORECA",
    badgeColor: "#0284C7",
    ribbonColor: "#DC2626",
    presentation: "Bolsón 5 Kg (120 unidades)",
    weightGrams: 5000,
    priceUnit: 33000,
    price6: 32000,
    price12: 31000,
    priceWholesale: 31000,
    inStock: true,
    description: "Empaque económico por volumen para freír o desgranar en preparaciones mixtas.",
    image: "assets/images/products/bolson_embutidos.svg",
    popular: false
  },
  {
    id: "prod-1015",
    code: "1015",
    name: "Butifarra en Colágeno (125 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Costeña",
    badgeColor: "#D97706",
    ribbonColor: "#F59E0B",
    presentation: "Bolsón 5 Kg / 10 Lb (125 Un)",
    weightGrams: 5000,
    priceUnit: 38000,
    price6: 37000,
    price12: 35000,
    priceWholesale: 34000,
    inStock: true,
    description: "Butifarra tradicional con pimienta de olor y cocción al vapor. Perfecta para servir con limón y bollo.",
    image: "assets/images/products/bolson_embutidos.svg",
    popular: true
  },
  {
    id: "prod-1017",
    code: "1017",
    name: "Bolsón Butifarra Plástica (120 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Canastilla",
    badgeColor: "#059669",
    ribbonColor: "#F59E0B",
    presentation: "Bolsón 5 Kg (120 unidades)",
    weightGrams: 5000,
    priceUnit: 33000,
    price6: 32000,
    price12: 31000,
    priceWholesale: 30000,
    inStock: true,
    description: "Formato institucional para comidas rápidas y fritos callejeros.",
    image: "assets/images/products/bolson_embutidos.svg",
    popular: false
  },
  {
    id: "prod-00012008",
    code: "00012008",
    name: "Cervecero Mexicano Picante",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Picante Especial",
    badgeColor: "#DC2626",
    ribbonColor: "#EF4444",
    presentation: "Pieza 1.100 Kg",
    weightGrams: 1100,
    priceUnit: 13000,
    price6: 12000,
    price12: 11500,
    priceWholesale: 11000,
    inStock: true,
    description: "Salchichón de toque picante y textura firme, acompañante infalible de la cerveza y pasabocas.",
    image: "assets/images/products/salchichon.svg",
    popular: false
  },
  {
    id: "prod-5408",
    code: "5408",
    name: "Salchichón Cervecero Fino",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Clásico",
    badgeColor: "#C1121F",
    ribbonColor: "#DC2626",
    presentation: "Pieza 900 gr",
    weightGrams: 900,
    priceUnit: 18000,
    price6: 17000,
    price12: 16800,
    priceWholesale: 16300,
    inStock: true,
    description: "Elaborado con cortes finos de res y cerdo, condimentación balanceada de receta de la casa.",
    image: "assets/images/products/salchichon.svg",
    popular: true
  },
  {
    id: "prod-1028",
    code: "1028",
    name: "Salchichón Corriente",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Económico",
    badgeColor: "#4B5563",
    ribbonColor: "#9CA3AF",
    presentation: "Pieza 600 gr",
    weightGrams: 600,
    priceUnit: 4000,
    price6: 3900,
    price12: 3800,
    priceWholesale: 3600,
    inStock: true,
    description: "Excelente relación precio-volumen para tiendas y desayunos tradicionales.",
    image: "assets/images/products/salchichon.svg",
    popular: false
  },
  {
    id: "prod-1423",
    code: "1423",
    name: "Salchichón de Pollo Seleccionado",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Pollo 100%",
    badgeColor: "#F59E0B",
    ribbonColor: "#FBBF24",
    presentation: "Pieza 600 gr",
    weightGrams: 600,
    priceUnit: 4000,
    price6: 3900,
    price12: 3800,
    priceWholesale: 3600,
    inStock: true,
    description: "Elaborado con pechuga y carne blanca de pollo, ligero y fácil de digerir.",
    image: "assets/images/products/salchichon.svg",
    popular: false
  },
  {
    id: "prod-12341",
    code: "12341",
    name: "Salchicha Suiza Artesanal (4 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Hot Dog Gourmet",
    badgeColor: "#7C3AED",
    ribbonColor: "#8B5CF6",
    presentation: "500 gr (4 unidades)",
    weightGrams: 500,
    priceUnit: 15000,
    price6: 14500,
    price12: 14000,
    priceWholesale: 13500,
    inStock: true,
    description: "Salchicha de textura crujiente y mordisco perfecto al estilo europeo. La favorita de carritos de perros calientes especiales.",
    image: "assets/images/products/salchicha_suiza.svg",
    popular: true
  },
  {
    id: "prod-12342",
    code: "12342",
    name: "Salchicha Suiza Artesanal (3 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Calidad Suiza",
    badgeColor: "#7C3AED",
    ribbonColor: "#8B5CF6",
    presentation: "375 gr (3 unidades)",
    weightGrams: 375,
    priceUnit: 11000,
    price6: 10800,
    price12: 11000,
    priceWholesale: 10500,
    inStock: true,
    description: "Porción de 3 unidades para cenas gourmet en casa.",
    image: "assets/images/products/salchicha_suiza.svg",
    popular: false
  },
  {
    id: "prod-234532",
    code: "234532",
    name: "Suiza Salchicha Institucional (8 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Formato Kilo",
    badgeColor: "#0284C7",
    ribbonColor: "#8B5CF6",
    presentation: "1.000 gr (8 unidades)",
    weightGrams: 1000,
    priceUnit: 30000,
    price6: 29000,
    price12: 28000,
    priceWholesale: 26000,
    inStock: true,
    description: "Paquete de 1 Kilo para asadores y restaurantes de comida rápida.",
    image: "assets/images/products/salchicha_suiza.svg",
    popular: false
  },
  {
    id: "prod-1031",
    code: "1031",
    name: "Manguera Tres Carnes Larga (16 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Alto Rendimiento",
    badgeColor: "#059669",
    ribbonColor: "#10B981",
    presentation: "2.750 Kg (16 unidades)",
    weightGrams: 2750,
    priceUnit: 27000,
    price6: 25000,
    price12: 24000,
    priceWholesale: 22000,
    inStock: true,
    description: "Combinación de res, cerdo y pollo en tripa continua para asaderos de alto flujo.",
    image: "assets/images/products/bolson_embutidos.svg",
    popular: false
  },
  {
    id: "prod-1256",
    code: "1256",
    name: "Carne Mexicano Materia Prima P.P.",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Insumo Especial",
    badgeColor: "#B91C1C",
    ribbonColor: "#EF4444",
    presentation: "Porción Kilo",
    weightGrams: 1000,
    priceUnit: 10000,
    price6: 9800,
    price12: 9500,
    priceWholesale: 9300,
    inStock: true,
    description: "Base cárnica sazonada lista para rellenos de empanadas, burritos y guisados.",
    image: "assets/images/products/salchichon.svg",
    popular: false
  },

  // --- TOCINETAS, JAMONES Y AHUMADOS ---
  {
    id: "prod-1005",
    code: "1005",
    name: "Tocineta Ahumada Especial en Láminas 1 Kg",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Top Ventas",
    badgeColor: "#C1121F",
    ribbonColor: "#B91C1C",
    presentation: "Paquete 1.000 gr",
    weightGrams: 1000,
    priceUnit: 22000,
    price6: 21000,
    price12: 20000,
    priceWholesale: 18000,
    inStock: true,
    description: "Láminas perfectas de tocineta curada y ahumada con maderas nobles. Queda crocante, dorada y sin encogerse en exceso. Para hamburgueserías de primer nivel.",
    image: "assets/images/products/tocineta_ahumada.svg",
    popular: true
  },
  {
    id: "prod-1006",
    code: "1006",
    name: "Tocineta Ahumada Especial 500 gr",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Recomendado",
    badgeColor: "#D97706",
    ribbonColor: "#B91C1C",
    presentation: "Paquete 500 gr",
    weightGrams: 500,
    priceUnit: 12000,
    price6: 11000,
    price12: 10000,
    priceWholesale: 9000,
    inStock: true,
    description: "Formato mediano ideal para el hogar y restaurantes que manejan menú de fin de semana.",
    image: "assets/images/products/tocineta_ahumada.svg",
    popular: true
  },
  {
    id: "prod-1007",
    code: "1007",
    name: "Tocineta Ahumada 250 gr",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Hogar",
    badgeColor: "#4B5563",
    ribbonColor: "#B91C1C",
    presentation: "Paquete 250 gr",
    weightGrams: 250,
    priceUnit: 7000,
    price6: 6800,
    price12: 6600,
    priceWholesale: 6300,
    inStock: true,
    description: "Porción de tocineta para el desayuno familiar de domingo.",
    image: "assets/images/products/tocineta_ahumada.svg",
    popular: false
  },
  {
    id: "prod-1008",
    code: "1008",
    name: "Tocineta Ahumada 125 gr",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Express",
    badgeColor: "#6B7280",
    ribbonColor: "#B91C1C",
    presentation: "Paquete 125 gr",
    weightGrams: 125,
    priceUnit: 4500,
    price6: 4300,
    price12: 4200,
    priceWholesale: 4000,
    inStock: true,
    description: "Presentación individual para antojos rápidos.",
    image: "assets/images/products/tocineta_ahumada.svg",
    popular: false
  },
  {
    id: "prod-4520",
    code: "4520",
    name: "Recorte de Tocineta Ahumada",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Ahorro Sabor",
    badgeColor: "#059669",
    ribbonColor: "#B91C1C",
    presentation: "Paquete 500 gr",
    weightGrams: 500,
    priceUnit: 7800,
    price6: 7500,
    price12: 7300,
    priceWholesale: 6800,
    inStock: true,
    description: "Trozos y puntas de tocineta de excelente calidad para saborizar frijoles, lentejas, arroces y salsas carbonara.",
    image: "assets/images/products/tocineta_ahumada.svg",
    popular: true
  },
  {
    id: "prod-12",
    code: "12",
    name: "Jamón Ahumado Tajado (27 Un)",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Sándwich Ideal",
    badgeColor: "#2563EB",
    ribbonColor: "#F43F5E",
    presentation: "500 gr (27 lonchas)",
    weightGrams: 500,
    priceUnit: 8000,
    price6: 7800,
    price12: 7500,
    priceWholesale: 7200,
    inStock: true,
    description: "Jamón cocido y ligeramente ahumado, lonchas uniformes que separan fácil sin romperse.",
    image: "assets/images/products/jamon_ahumado.svg",
    popular: true
  },
  {
    id: "prod-1004",
    code: "1004",
    name: "Jamón Ahumado Tajado 250 gr",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Práctico",
    badgeColor: "#4B5563",
    ribbonColor: "#F43F5E",
    presentation: "250 gr",
    weightGrams: 250,
    priceUnit: 4600,
    price6: 4400,
    price12: 4200,
    priceWholesale: 4000,
    inStock: true,
    description: "Porción de 250 gramos de jamón ahumado.",
    image: "assets/images/products/jamon_ahumado.svg",
    popular: false
  },
  {
    id: "prod-1001",
    code: "1001",
    name: "Jamón Ranchero Sabor Intenso",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Receta Ranchera",
    badgeColor: "#C1121F",
    ribbonColor: "#F43F5E",
    presentation: "500 gr",
    weightGrams: 500,
    priceUnit: 8000,
    price6: 7800,
    price12: 7500,
    priceWholesale: 7200,
    inStock: true,
    description: "Sabor especiado con páprika y humo de nogal para desayunos con huevos y sándwiches gourmet.",
    image: "assets/images/products/jamon_ahumado.svg",
    popular: true
  },
  {
    id: "prod-1033",
    code: "1033",
    name: "Jamón Ranchero 250 gr",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Porción Diaria",
    badgeColor: "#4B5563",
    ribbonColor: "#F43F5E",
    presentation: "250 gr",
    weightGrams: 250,
    priceUnit: 4600,
    price6: 4400,
    price12: 4200,
    priceWholesale: 4000,
    inStock: true,
    description: "Presentación de 250 gr de jamón ranchero.",
    image: "assets/images/products/jamon_ahumado.svg",
    popular: false
  },
  {
    id: "prod-1009",
    code: "1009",
    name: "Hamburguesa Ahumada Parrillera (6 Un)",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Parrilla Directa",
    badgeColor: "#EA580C",
    ribbonColor: "#DC2626",
    presentation: "500 gr (6 unidades)",
    weightGrams: 500,
    priceUnit: 10000,
    price6: 9800,
    price12: 9700,
    priceWholesale: 9500,
    inStock: true,
    description: "Carne para hamburguesa sazonada con toque ahumado, listas para asar sin desarmarse.",
    image: "assets/images/products/hamburguesa.svg",
    popular: true
  },

  // --- LÍNEA INSTITUCIONAL, INSUMOS Y PRODUCTOS AGOTADOS / TEMPORADA ---
  {
    id: "prod-6711",
    code: "6711",
    name: "Rollo Térmico 80x60 para Punto de Venta",
    category: "institucional",
    categoryName: "Línea Especial e Insumos",
    badge: "Insumo POS",
    badgeColor: "#0284C7",
    ribbonColor: "#64748B",
    presentation: "Rollo 80x60 mm",
    weightGrams: 150,
    priceUnit: 6000,
    price6: 5800,
    price12: 5500,
    priceWholesale: 5200,
    inStock: true,
    description: "Papel térmico de alta sensibilidad para facturación electrónica y datáfonos de minimercados.",
    image: "assets/images/products/rollo_termico.svg",
    popular: false
  },
  {
    id: "prod-1234",
    code: "1234",
    name: "Jamón Premium 500 gr (27 Un)",
    category: "ahumados",
    categoryName: "Tocineta y Ahumados",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "500 gr",
    weightGrams: 500,
    priceUnit: 9000,
    price6: 8700,
    price12: 8500,
    priceWholesale: 8000,
    inStock: false,
    description: "Corte de pierna premium curado. Temporalmente fuera de stock.",
    image: "assets/images/products/jamon_ahumado.svg",
    popular: false
  },
  {
    id: "prod-0087",
    code: "0087",
    name: "Mortadela Jamonada 2.500 gr",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "Pieza 2.500 gr",
    weightGrams: 2500,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Pieza entera para rebanar en salsamentarias. Temporalmente agotado.",
    image: "assets/images/products/salchichon.svg",
    popular: false
  },
  {
    id: "prod-1091",
    code: "1091",
    name: "Pernil Navideño Horneado",
    category: "institucional",
    categoryName: "Línea Especial e Insumos",
    badge: "Temporada Navideña",
    badgeColor: "#C1121F",
    ribbonColor: "#DC2626",
    presentation: "Desde 1 Kilo en adelante",
    weightGrams: 1000,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Pernil de cerdo ahumado con glaseado de ciruelas y clavos. Disponible por encargo en temporada decembrina.",
    image: "assets/images/products/pernil_navideno.svg",
    popular: false
  },
  {
    id: "prod-1080",
    code: "1080",
    name: "Pavo Navideño Relleno",
    category: "institucional",
    categoryName: "Línea Especial e Insumos",
    badge: "Temporada Navideña",
    badgeColor: "#C1121F",
    ribbonColor: "#DC2626",
    presentation: "Desde 1 Kilo en adelante",
    weightGrams: 1000,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Pavo sazonado para cenas corporativas y familiares. Disponible por encargo en fin de año.",
    image: "assets/images/products/pernil_navideno.svg",
    popular: false
  },
  {
    id: "prod-1019",
    code: "1019",
    name: "Salchicha Hot Dog (6 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "500 gr (6 unidades)",
    weightGrams: 500,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Salchicha clásica para perro caliente casero. Temporalmente agotado.",
    image: "assets/images/products/salchicha_suiza.svg",
    popular: false
  },
  {
    id: "prod-1018",
    code: "1018",
    name: "Salchicha Ranchera (16 Un)",
    category: "chorizos",
    categoryName: "Chorizos y Cárnicos",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "500 gr (16 unidades)",
    weightGrams: 500,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Salchicha ranchera con queso y tocino. Temporalmente agotada.",
    image: "assets/images/products/salchicha_suiza.svg",
    popular: false
  },
  {
    id: "prod-125854",
    code: "125854",
    name: "Pimpina de Aceite Vegetal 17 Litros",
    category: "institucional",
    categoryName: "Línea Especial e Insumos",
    badge: "Agotado",
    badgeColor: "#6B7280",
    ribbonColor: "#9CA3AF",
    presentation: "Garrafa 17 Litros",
    weightGrams: 16000,
    priceUnit: 0,
    price6: 0,
    price12: 0,
    priceWholesale: 0,
    inStock: false,
    description: "Aceite vegetal para fritura profunda en restaurantes y piqueteaderos. Temporalmente fuera de inventario.",
    image: "assets/images/products/rollo_termico.svg",
    popular: false
  }
];

// Helper para formatear moneda colombiana
function formatCOP(amount) {
  if (!amount || amount === 0) return "Consultar";
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount);
}

// Configuración general de la empresa
const COMPANY_INFO = {
  name: "Distribuciones La Montaña S.A.S.",
  brand: "La Montaña Aaron",
  nit: "901712016",
  whatsappNumber: "+57 311 3066782",
  whatsappClean: "573113066782",
  city: "Bogotá D.C. & Cobertura Nacional",
  deliveryNote: "Despachos refrigerados en vehículo termoking garantizado",
  minWholesaleAmount: 150000
};
